# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /edfs/users/namvu/chem/deprince-group/plugins/erpa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /edfs/users/namvu/chem/deprince-group/plugins/erpa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /edfs/users/namvu/chem/deprince-group/plugins/erpa/CMakeFiles /edfs/users/namvu/chem/deprince-group/plugins/erpa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /edfs/users/namvu/chem/deprince-group/plugins/erpa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named erpa

# Build rule for target.
erpa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erpa
.PHONY : erpa

# fast build rule for target.
erpa/fast:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/build
.PHONY : erpa/fast

basis.o: basis.cc.o

.PHONY : basis.o

# target to build an object file
basis.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/basis.cc.o
.PHONY : basis.cc.o

basis.i: basis.cc.i

.PHONY : basis.i

# target to preprocess a source file
basis.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/basis.cc.i
.PHONY : basis.cc.i

basis.s: basis.cc.s

.PHONY : basis.s

# target to generate assembly for a file
basis.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/basis.cc.s
.PHONY : basis.cc.s

blas.o: blas.cc.o

.PHONY : blas.o

# target to build an object file
blas.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/blas.cc.o
.PHONY : blas.cc.o

blas.i: blas.cc.i

.PHONY : blas.i

# target to preprocess a source file
blas.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/blas.cc.i
.PHONY : blas.cc.i

blas.s: blas.cc.s

.PHONY : blas.s

# target to generate assembly for a file
blas.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/blas.cc.s
.PHONY : blas.cc.s

erpa.o: erpa.cc.o

.PHONY : erpa.o

# target to build an object file
erpa.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/erpa.cc.o
.PHONY : erpa.cc.o

erpa.i: erpa.cc.i

.PHONY : erpa.i

# target to preprocess a source file
erpa.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/erpa.cc.i
.PHONY : erpa.cc.i

erpa.s: erpa.cc.s

.PHONY : erpa.s

# target to generate assembly for a file
erpa.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/erpa.cc.s
.PHONY : erpa.cc.s

erpa_solver.o: erpa_solver.cc.o

.PHONY : erpa_solver.o

# target to build an object file
erpa_solver.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/erpa_solver.cc.o
.PHONY : erpa_solver.cc.o

erpa_solver.i: erpa_solver.cc.i

.PHONY : erpa_solver.i

# target to preprocess a source file
erpa_solver.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/erpa_solver.cc.i
.PHONY : erpa_solver.cc.i

erpa_solver.s: erpa_solver.cc.s

.PHONY : erpa_solver.s

# target to generate assembly for a file
erpa_solver.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/erpa_solver.cc.s
.PHONY : erpa_solver.cc.s

ip_erpa.o: ip_erpa.cc.o

.PHONY : ip_erpa.o

# target to build an object file
ip_erpa.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/ip_erpa.cc.o
.PHONY : ip_erpa.cc.o

ip_erpa.i: ip_erpa.cc.i

.PHONY : ip_erpa.i

# target to preprocess a source file
ip_erpa.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/ip_erpa.cc.i
.PHONY : ip_erpa.cc.i

ip_erpa.s: ip_erpa.cc.s

.PHONY : ip_erpa.s

# target to generate assembly for a file
ip_erpa.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/ip_erpa.cc.s
.PHONY : ip_erpa.cc.s

read_3pdm.o: read_3pdm.cc.o

.PHONY : read_3pdm.o

# target to build an object file
read_3pdm.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_3pdm.cc.o
.PHONY : read_3pdm.cc.o

read_3pdm.i: read_3pdm.cc.i

.PHONY : read_3pdm.i

# target to preprocess a source file
read_3pdm.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_3pdm.cc.i
.PHONY : read_3pdm.cc.i

read_3pdm.s: read_3pdm.cc.s

.PHONY : read_3pdm.s

# target to generate assembly for a file
read_3pdm.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_3pdm.cc.s
.PHONY : read_3pdm.cc.s

read_opdm.o: read_opdm.cc.o

.PHONY : read_opdm.o

# target to build an object file
read_opdm.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_opdm.cc.o
.PHONY : read_opdm.cc.o

read_opdm.i: read_opdm.cc.i

.PHONY : read_opdm.i

# target to preprocess a source file
read_opdm.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_opdm.cc.i
.PHONY : read_opdm.cc.i

read_opdm.s: read_opdm.cc.s

.PHONY : read_opdm.s

# target to generate assembly for a file
read_opdm.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_opdm.cc.s
.PHONY : read_opdm.cc.s

read_tpdm.o: read_tpdm.cc.o

.PHONY : read_tpdm.o

# target to build an object file
read_tpdm.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_tpdm.cc.o
.PHONY : read_tpdm.cc.o

read_tpdm.i: read_tpdm.cc.i

.PHONY : read_tpdm.i

# target to preprocess a source file
read_tpdm.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_tpdm.cc.i
.PHONY : read_tpdm.cc.i

read_tpdm.s: read_tpdm.cc.s

.PHONY : read_tpdm.s

# target to generate assembly for a file
read_tpdm.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/read_tpdm.cc.s
.PHONY : read_tpdm.cc.s

sortintegrals.o: sortintegrals.cc.o

.PHONY : sortintegrals.o

# target to build an object file
sortintegrals.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/sortintegrals.cc.o
.PHONY : sortintegrals.cc.o

sortintegrals.i: sortintegrals.cc.i

.PHONY : sortintegrals.i

# target to preprocess a source file
sortintegrals.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/sortintegrals.cc.i
.PHONY : sortintegrals.cc.i

sortintegrals.s: sortintegrals.cc.s

.PHONY : sortintegrals.s

# target to generate assembly for a file
sortintegrals.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/sortintegrals.cc.s
.PHONY : sortintegrals.cc.s

tei.o: tei.cc.o

.PHONY : tei.o

# target to build an object file
tei.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/tei.cc.o
.PHONY : tei.cc.o

tei.i: tei.cc.i

.PHONY : tei.i

# target to preprocess a source file
tei.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/tei.cc.i
.PHONY : tei.cc.i

tei.s: tei.cc.s

.PHONY : tei.s

# target to generate assembly for a file
tei.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/tei.cc.s
.PHONY : tei.cc.s

threeindexintegrals.o: threeindexintegrals.cc.o

.PHONY : threeindexintegrals.o

# target to build an object file
threeindexintegrals.cc.o:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/threeindexintegrals.cc.o
.PHONY : threeindexintegrals.cc.o

threeindexintegrals.i: threeindexintegrals.cc.i

.PHONY : threeindexintegrals.i

# target to preprocess a source file
threeindexintegrals.cc.i:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/threeindexintegrals.cc.i
.PHONY : threeindexintegrals.cc.i

threeindexintegrals.s: threeindexintegrals.cc.s

.PHONY : threeindexintegrals.s

# target to generate assembly for a file
threeindexintegrals.cc.s:
	$(MAKE) -f CMakeFiles/erpa.dir/build.make CMakeFiles/erpa.dir/threeindexintegrals.cc.s
.PHONY : threeindexintegrals.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... erpa"
	@echo "... edit_cache"
	@echo "... basis.o"
	@echo "... basis.i"
	@echo "... basis.s"
	@echo "... blas.o"
	@echo "... blas.i"
	@echo "... blas.s"
	@echo "... erpa.o"
	@echo "... erpa.i"
	@echo "... erpa.s"
	@echo "... erpa_solver.o"
	@echo "... erpa_solver.i"
	@echo "... erpa_solver.s"
	@echo "... ip_erpa.o"
	@echo "... ip_erpa.i"
	@echo "... ip_erpa.s"
	@echo "... read_3pdm.o"
	@echo "... read_3pdm.i"
	@echo "... read_3pdm.s"
	@echo "... read_opdm.o"
	@echo "... read_opdm.i"
	@echo "... read_opdm.s"
	@echo "... read_tpdm.o"
	@echo "... read_tpdm.i"
	@echo "... read_tpdm.s"
	@echo "... sortintegrals.o"
	@echo "... sortintegrals.i"
	@echo "... sortintegrals.s"
	@echo "... tei.o"
	@echo "... tei.i"
	@echo "... tei.s"
	@echo "... threeindexintegrals.o"
	@echo "... threeindexintegrals.i"
	@echo "... threeindexintegrals.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

